"""
Demo data for Villa Aigea Hotel — a boutique luxury property on the Greek island of Evia.
All data is fictional and for demonstration purposes only.
"""

HOTEL_INFO = {
    "name": "Villa Aigea",
    "tagline": "Where the Aegean Whispers",
    "category": "Boutique Luxury Hotel",
    "stars": 5,
    "location": {
        "address": "Limni Evia, 34005",
        "island": "Evia",
        "country": "Greece",
        "region": "Central Greece",
        "coordinates": {"lat": 38.7862, "lon": 23.3063},
    },
    "contact": {
        "phone": "+30 22270 31500",
        "email": "reservations@villaaigea.gr",
        "website": "www.villaaigea.gr",
    },
    "description": (
        "Villa Aigea is an intimate boutique hotel perched on the northern coast of Evia, "
        "overlooking the turquoise waters of the Euboean Gulf. The property features 18 "
        "individually designed rooms and suites set within a restored 19th-century Neo-Classical "
        "villa surrounded by lush pine and olive gardens. Guests enjoy a private beach, "
        "a spa, an award-winning restaurant, and the unhurried pace of authentic Greek island life."
    ),
    "established": 1998,
    "total_rooms": 18,
    "check_in_time": "15:00",
    "check_out_time": "12:00",
    "languages_spoken": ["Greek", "English", "French", "German", "Italian"],
    "awards": [
        "Condé Nast Traveller Greece Top 10 Boutique Hotels (2023)",
        "TripAdvisor Travellers' Choice Award (2022, 2023, 2024)",
        "World Luxury Hotel Awards — Boutique Hotel of the Year Greece (2023)",
    ],
    "facilities": [
        "Private beach with sunbeds and umbrellas",
        "Heated outdoor swimming pool (April–October)",
        "Spa & wellness centre with sauna, steam room, jacuzzi",
        "Award-winning restaurant 'Thalassa' (Mediterranean cuisine)",
        "Pool bar 'Delphi'",
        "Library lounge",
        "Concierge and 24-hour reception",
        "Private parking",
        "Boat rental and water sports",
        "Daily guided hiking tours",
        "In-room dining (06:00–23:00)",
        "Complimentary high-speed Wi-Fi throughout",
        "Laundry and dry-cleaning service",
        "Airport/port transfers by arrangement",
        "Events and private dining room (up to 30 guests)",
    ],
    "pet_policy": "Small pets (up to 8 kg) welcome in garden-view rooms with prior arrangement.",
    "sustainability": "Green Key certified; solar-heated water, organic kitchen garden, no single-use plastics.",
    "season": "Open April 1 – October 31",
}

ROOM_TYPES = [
    {
        "room_id": "STD-GV-01",
        "type": "Standard Garden View",
        "category": "Standard",
        "floor": 1,
        "size_sqm": 28,
        "max_adults": 2,
        "max_children": 1,
        "max_occupancy": 3,
        "bed_configuration": "1 King (can split to 2 Twin)",
        "view": "Garden",
        "price_per_night": 180,
        "currency": "EUR",
        "description": (
            "A comfortable and tastefully furnished room on the ground floor, opening onto "
            "the hotel's fragrant olive-and-lavender garden via a private terrace. "
            "Ideal for guests who enjoy close contact with nature."
        ),
        "amenities": [
            "Private terrace with garden seating",
            "Air conditioning",
            "Free Wi-Fi",
            "55″ Smart TV",
            "Nespresso machine",
            "Minibar",
            "In-room safe",
            "Marble en-suite bathroom with rain shower",
            "L'Occitane toiletries",
            "Bathrobes and slippers",
            "Daily housekeeping",
            "Complimentary welcome bottle of Evia wine",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "STD-GV-02",
        "type": "Standard Garden View",
        "category": "Standard",
        "floor": 1,
        "size_sqm": 28,
        "max_adults": 2,
        "max_children": 1,
        "max_occupancy": 3,
        "bed_configuration": "2 Twin",
        "view": "Garden",
        "price_per_night": 180,
        "currency": "EUR",
        "description": (
            "Twin-bed configuration of our Garden View room, perfect for friends or "
            "travelling colleagues. Ground-floor terrace access."
        ),
        "amenities": [
            "Private terrace with garden seating",
            "Air conditioning",
            "Free Wi-Fi",
            "55″ Smart TV",
            "Nespresso machine",
            "Minibar",
            "In-room safe",
            "Marble en-suite bathroom with rain shower",
            "L'Occitane toiletries",
            "Bathrobes and slippers",
            "Daily housekeeping",
            "Complimentary welcome bottle of Evia wine",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "SUP-SV-03",
        "type": "Superior Sea View",
        "category": "Superior",
        "floor": 2,
        "size_sqm": 35,
        "max_adults": 2,
        "max_children": 1,
        "max_occupancy": 3,
        "bed_configuration": "1 King",
        "view": "Euboean Gulf",
        "price_per_night": 260,
        "currency": "EUR",
        "description": (
            "Second-floor rooms with panoramic views of the Euboean Gulf. "
            "The private balcony is the ideal spot for a slow Greek breakfast or a sundowner. "
            "Furnished with hand-painted local ceramics and silk cushions in Aegean blue."
        ),
        "amenities": [
            "Private balcony with sea-view seating",
            "Air conditioning",
            "Free Wi-Fi",
            "55″ Smart TV",
            "Nespresso & Numi tea station",
            "Minibar with local spirits",
            "In-room safe",
            "Marble en-suite bathroom with rain shower and freestanding tub",
            "L'Occitane toiletries",
            "Bathrobes and slippers",
            "Daily housekeeping and turndown service",
            "Complimentary local wine and fruit basket on arrival",
            "Beach bag, towels and sunscreen set",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "SUP-SV-04",
        "type": "Superior Sea View",
        "category": "Superior",
        "floor": 2,
        "size_sqm": 35,
        "max_adults": 2,
        "max_children": 1,
        "max_occupancy": 3,
        "bed_configuration": "1 King",
        "view": "Euboean Gulf",
        "price_per_night": 260,
        "currency": "EUR",
        "description": (
            "Mirror of room 03 on the opposite wing; the balcony faces the morning sun "
            "for spectacular sunrises over the gulf."
        ),
        "amenities": [
            "Private balcony with sea-view seating",
            "Air conditioning",
            "Free Wi-Fi",
            "55″ Smart TV",
            "Nespresso & Numi tea station",
            "Minibar with local spirits",
            "In-room safe",
            "Marble en-suite bathroom with rain shower and freestanding tub",
            "L'Occitane toiletries",
            "Bathrobes and slippers",
            "Daily housekeeping and turndown service",
            "Complimentary local wine and fruit basket on arrival",
            "Beach bag, towels and sunscreen set",
        ],
        "availability_status": "maintenance",
    },
    {
        "room_id": "JRS-SV-05",
        "type": "Junior Suite Sea View",
        "category": "Junior Suite",
        "floor": 2,
        "size_sqm": 52,
        "max_adults": 2,
        "max_children": 2,
        "max_occupancy": 4,
        "bed_configuration": "1 Super King + sofa bed",
        "view": "Euboean Gulf & garden",
        "price_per_night": 390,
        "currency": "EUR",
        "description": (
            "A generous step up in space and luxury. The living area features hand-loom "
            "rugs, a Chesterfield-style sofa, and local artwork. The separate bedroom "
            "opens onto a wide wrap-around balcony that catches both sunrise and sunset."
        ),
        "amenities": [
            "Wrap-around private balcony",
            "Separate living area with sofa bed",
            "Air conditioning",
            "Free Wi-Fi",
            "65″ Smart TV in bedroom + 43″ in lounge",
            "Nespresso machine",
            "Fully stocked minibar",
            "In-room safe (laptop size)",
            "Marble bathroom: rain shower, soaking tub, double vanity",
            "Molton Brown toiletries",
            "Bathrobes, slippers and luxury amenity kit",
            "Twice-daily housekeeping and evening turndown",
            "Welcome amenity: Champagne, local cheeses, and honey",
            "Complimentary pressing of 3 garments on arrival",
            "Priority beach chair reservation",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "STE-SV-06",
        "type": "Aigea Suite",
        "category": "Suite",
        "floor": 3,
        "size_sqm": 75,
        "max_adults": 2,
        "max_children": 2,
        "max_occupancy": 4,
        "bed_configuration": "1 Super King",
        "view": "360° panoramic — sea, village and mountains",
        "price_per_night": 580,
        "currency": "EUR",
        "description": (
            "Our flagship suite occupies the entire third floor of the original villa. "
            "Soaring ceilings with restored frescoes, antique Ionian furnishings, and "
            "a private terrace with an outdoor rain shower and heated plunge pool. "
            "The Aigea Suite is our most-requested accommodation and regularly hosts "
            "honeymoon couples and anniversary celebrants."
        ),
        "amenities": [
            "Private terrace with outdoor rain shower and plunge pool",
            "Separate dressing room",
            "Living room with antique furnishings and original frescoes",
            "Air conditioning and underfloor heating",
            "Free Wi-Fi",
            "75″ Smart TV + Bang & Olufsen sound system",
            "Nespresso machine and full cocktail bar",
            "In-room safe (laptop size)",
            "Grand marble bathroom: double rain shower, freestanding copper tub, double vanity",
            "ESPA personalised toiletries",
            "Bathrobes, slippers and deluxe amenity kit",
            "Butler service 08:00–22:00",
            "Daily housekeeping twice daily plus evening turndown",
            "Welcome amenity: personalised wine selection, flowers, fruit, chocolates",
            "Complimentary airport/port transfers (one round trip)",
            "Complimentary spa treatment (one per stay, per guest)",
            "Priority restaurant reservations",
            "Private beach cabana reserved for duration of stay",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "VIL-BV-07",
        "type": "Beach Villa",
        "category": "Villa",
        "floor": 0,
        "size_sqm": 110,
        "max_adults": 4,
        "max_children": 2,
        "max_occupancy": 6,
        "bed_configuration": "1 Super King (master) + 1 Queen (second bedroom)",
        "view": "Direct beach frontage",
        "price_per_night": 950,
        "currency": "EUR",
        "description": (
            "A standalone beachfront villa with direct access to the private beach. "
            "Two bedrooms, a fully equipped kitchen, a private garden, and an outdoor "
            "dining area with BBQ. Ideal for families or couples seeking total privacy. "
            "The villa can accommodate up to 6 guests with the addition of two sofa beds "
            "in the lounge."
        ),
        "amenities": [
            "Private garden with direct beach access",
            "Outdoor dining area and BBQ",
            "Private swimming pool (12m×5m, heated on request)",
            "2 bedrooms + lounge with sofa beds",
            "Fully equipped modern kitchen",
            "2 full bathrooms + guest WC",
            "Air conditioning in all rooms",
            "Free Wi-Fi",
            "75″ Smart TV in lounge + 55″ in master bedroom",
            "Nespresso machine and fully stocked minibar",
            "In-room safe (laptop size)",
            "ESPA personalised toiletries (×2 bathrooms)",
            "Bathrobes and slippers for all guests",
            "Daily housekeeping and evening turndown",
            "Dedicated villa host 08:00–20:00",
            "Welcome provisions: local wine, olive oil, honey, bread and fruit basket",
            "Complimentary airport/port transfers (one round trip)",
            "Complimentary spa treatment per guest (one per stay)",
            "Private beach area with sunbeds, umbrellas, and drinks service",
        ],
        "availability_status": "available",
    },
    {
        "room_id": "VIL-BV-08",
        "type": "Beach Villa",
        "category": "Villa",
        "floor": 0,
        "size_sqm": 110,
        "max_adults": 4,
        "max_children": 2,
        "max_occupancy": 6,
        "bed_configuration": "1 Super King (master) + 2 Twin (second bedroom)",
        "view": "Direct beach frontage",
        "price_per_night": 950,
        "currency": "EUR",
        "description": (
            "Sister villa to BV-07, with twin beds in the second bedroom — ideal for "
            "two couples or a family with older children. Identical amenities."
        ),
        "amenities": [
            "Private garden with direct beach access",
            "Outdoor dining area and BBQ",
            "Private swimming pool (12m×5m, heated on request)",
            "2 bedrooms + lounge with sofa beds",
            "Fully equipped modern kitchen",
            "2 full bathrooms + guest WC",
            "Air conditioning in all rooms",
            "Free Wi-Fi",
            "75″ Smart TV in lounge + 55″ in master bedroom",
            "Nespresso machine and fully stocked minibar",
            "In-room safe (laptop size)",
            "ESPA personalised toiletries (×2 bathrooms)",
            "Bathrobes and slippers for all guests",
            "Daily housekeeping and evening turndown",
            "Dedicated villa host 08:00–20:00",
            "Welcome provisions: local wine, olive oil, honey, bread and fruit basket",
            "Complimentary airport/port transfers (one round trip)",
            "Complimentary spa treatment per guest (one per stay)",
            "Private beach area with sunbeds, umbrellas, and drinks service",
        ],
        "availability_status": "occupied",
    },
]

# Simulated reservations (demo: some rooms occupied on certain dates)
EXISTING_RESERVATIONS = [
    {
        "reservation_id": "RES-2025-0412",
        "room_id": "VIL-BV-08",
        "guest_name": "Papadopoulos, Eleni",
        "check_in": "2025-07-24",
        "check_out": "2025-08-02",
        "adults": 2,
        "children": 2,
        "special_requests": "Early check-in if possible; hypoallergenic pillows",
        "vip_level": None,
    },
    {
        "reservation_id": "RES-2025-0398",
        "room_id": "SUP-SV-04",
        "guest_name": "Maintenance Block",
        "check_in": "2025-07-20",
        "check_out": "2025-07-28",
        "adults": 0,
        "children": 0,
        "special_requests": "Bathroom retiling; room offline",
        "vip_level": None,
    },
    {
        "reservation_id": "RES-2025-0418",
        "room_id": "STE-SV-06",
        "guest_name": "Rossi, Marco & Sofia",
        "check_in": "2025-07-27",
        "check_out": "2025-07-31",
        "adults": 2,
        "children": 0,
        "special_requests": "Honeymoon couple; rose petal turndown night 1; champagne on arrival",
        "vip_level": "Gold",
    },
    {
        "reservation_id": "RES-2025-0421",
        "room_id": "JRS-SV-05",
        "guest_name": "Yamamoto, Hiroshi",
        "check_in": "2025-07-29",
        "check_out": "2025-08-05",
        "adults": 2,
        "children": 1,
        "special_requests": "Gluten-free meals for guest; child-safe pool supervision requested",
        "vip_level": "Platinum",
    },
    {
        "reservation_id": "RES-2025-0425",
        "room_id": "SUP-SV-03",
        "guest_name": "Al-Rashid, Fatima",
        "check_in": "2025-07-26",
        "check_out": "2025-07-30",
        "adults": 2,
        "children": 0,
        "special_requests": "Halal meal options; no alcohol in minibar",
        "vip_level": "Silver",
    },
    {
        "reservation_id": "RES-2025-0427",
        "room_id": "STD-GV-01",
        "guest_name": "Müller, Klaus",
        "check_in": "2025-07-28",
        "check_out": "2025-08-01",
        "adults": 2,
        "children": 1,
        "special_requests": "High chair for breakfast; cot in room",
        "vip_level": None,
    },
]

# Upsell offerings
UPSELL_CATALOG = {
    "spa": [
        {
            "id": "SPA-001",
            "name": "Aegean Ritual (90 min)",
            "description": "Full-body sea-salt scrub, warm olive oil massage, and scalp treatment.",
            "price": 180,
            "currency": "EUR",
            "suitable_for": "couples, individuals",
        },
        {
            "id": "SPA-002",
            "name": "Couples Sunset Massage (60 min)",
            "description": "Side-by-side aromatherapy massage in the rooftop pavilion at sunset.",
            "price": 250,
            "currency": "EUR",
            "suitable_for": "couples",
        },
        {
            "id": "SPA-003",
            "name": "Hydra Facial",
            "description": "Multi-step hydrating facial tailored to your skin type.",
            "price": 120,
            "currency": "EUR",
            "suitable_for": "individuals",
        },
    ],
    "dining": [
        {
            "id": "DIN-001",
            "name": "Private Beach Dinner",
            "description": "5-course tasting menu served on the private beach with candlelight and live guitar.",
            "price": 320,
            "currency": "EUR",
            "per": "per couple",
        },
        {
            "id": "DIN-002",
            "name": "Greek Wine Tasting",
            "description": "Guided tasting of 6 premium Greek wines with paired mezze, led by our sommelier.",
            "price": 85,
            "currency": "EUR",
            "per": "per person",
        },
        {
            "id": "DIN-003",
            "name": "Cooking Class",
            "description": "Learn to cook 3 traditional Greek dishes with Head Chef Stavros Alexiou.",
            "price": 110,
            "currency": "EUR",
            "per": "per person",
        },
    ],
    "experiences": [
        {
            "id": "EXP-001",
            "name": "Sunset Boat Trip",
            "description": "2-hour private sailing trip along the northern Evia coast at sunset.",
            "price": 380,
            "currency": "EUR",
            "per": "per boat (up to 6 guests)",
        },
        {
            "id": "EXP-002",
            "name": "Mountain Hike & Lunch",
            "description": "Half-day guided hike in Dirfys National Park with traditional taverna lunch.",
            "price": 65,
            "currency": "EUR",
            "per": "per person",
        },
        {
            "id": "EXP-003",
            "name": "Apiary & Honey Tasting",
            "description": "Visit the hotel's beehives with the beekeeper and taste estate honey varieties.",
            "price": 40,
            "currency": "EUR",
            "per": "per person",
        },
    ],
    "room_enhancements": [
        {
            "id": "ENH-001",
            "name": "Romance Package",
            "description": "Rose petals on bed, Champagne and chocolate truffles, scented candles, flower arrangement.",
            "price": 120,
            "currency": "EUR",
        },
        {
            "id": "ENH-002",
            "name": "Birthday Celebration Set-up",
            "description": "Balloon arrangement, personalised birthday cake, sparkling wine, greeting card.",
            "price": 95,
            "currency": "EUR",
        },
        {
            "id": "ENH-003",
            "name": "Pool Heating (Beach Villas)",
            "description": "Heat the private villa pool to 30 °C for the duration of your stay.",
            "price": 80,
            "currency": "EUR",
            "per": "per night",
        },
    ],
}

# Room readiness status (simulated housekeeping board)
ROOM_READINESS = [
    {
        "room_id": "STD-GV-01",
        "housekeeping_status": "clean",
        "inspection_passed": True,
        "last_cleaned": "2025-07-26 09:30",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": True,
    },
    {
        "room_id": "STD-GV-02",
        "housekeeping_status": "clean",
        "inspection_passed": True,
        "last_cleaned": "2025-07-26 09:50",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": True,
    },
    {
        "room_id": "SUP-SV-03",
        "housekeeping_status": "occupied_stay_over",
        "inspection_passed": None,
        "last_cleaned": "2025-07-26 10:15",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": False,
        "note": "Guest Al-Rashid in residence; DND sign displayed until 12:00",
    },
    {
        "room_id": "SUP-SV-04",
        "housekeeping_status": "maintenance",
        "inspection_passed": False,
        "last_cleaned": None,
        "minibar_restocked": False,
        "maintenance_issues": ["Bathroom floor retiling in progress — completion 28 Jul"],
        "ready_for_checkin": False,
    },
    {
        "room_id": "JRS-SV-05",
        "housekeeping_status": "clean",
        "inspection_passed": True,
        "last_cleaned": "2025-07-26 08:45",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": True,
        "note": "Welcome amenity set for Yamamoto arrival 29 Jul — champagne in fridge",
    },
    {
        "room_id": "STE-SV-06",
        "housekeeping_status": "pre-arrival_prep",
        "inspection_passed": True,
        "last_cleaned": "2025-07-26 11:00",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": True,
        "note": "Rossi honeymoon arrival 27 Jul — rose petals ordered; champagne in ice bucket; flower arrangement from Chalkida florist ETA 16:00",
    },
    {
        "room_id": "VIL-BV-07",
        "housekeeping_status": "clean",
        "inspection_passed": True,
        "last_cleaned": "2025-07-26 10:30",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": True,
        "note": "Pool heating tested and operational",
    },
    {
        "room_id": "VIL-BV-08",
        "housekeeping_status": "occupied_stay_over",
        "inspection_passed": None,
        "last_cleaned": "2025-07-25 10:00",
        "minibar_restocked": True,
        "maintenance_issues": [],
        "ready_for_checkin": False,
        "note": "Papadopoulos family in residence until 2 Aug; extra towels delivered this morning",
    },
]
